library(R.utils)
library(phytools)
library(diversitree)
library(geiger)
library(doMC)
library(foreach)
library(OUwie)
# cl<-makeCluster(3, type="SOCK")
# on.exit(stopCluster(cl))
opts <- list(preschedule = FALSE)
registerDoMC(125)

source('./Analyses/Discarded.Simulation.Counter.R')
rm(list = ls())
source('./Analyses/OUanalysis.R')
rm(list = ls())
source('./Analyses/Pagel.Threshold.R')
rm(list = ls())
source('./Analyses/Scaling.Analysis.Bidirectional.R')
rm(list = ls())
source('./Analyses/Scaling.Analysis.Unidirectional.R')
rm(list = ls())
source('./Analyses/Taxa.Analysis.Bidirectional.FP.R')
rm(list = ls())
source('./Analyses/Taxa.Analysis.Bidirectional.Power.R')
rm(list = ls())
source('./Analyses/Taxa.Analysis.Unidirectional.FP.R')
rm(list = ls())
source('./Analyses/Taxa.Analysis.Unidirectional.Power.R')
rm(list = ls())
source('./Analyses/Whale_Analysis.R')
rm(list = ls())